version: '3'
services:
  node:
    image: 'node:alpine'
    container_name: my_node
    user: 'node'
    working_dir: /app
    environment:
      - NODE_ENV=development
    volumes:
      - ./app:/app
    expose:
      - 9999
    ports:
      - 9999:9999
    command: 'npm run start'

  web:
    image: nginx
    container_name: my_nginx
    links:
      - node
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
    - "8080:80"

  mongo:
    container_name: my_mongo
    image: mongo
    volumes:
      - "my_mongodb:/data/db"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express:
    container_name: my_express
    image: mongo-express
    links:
      - mongo
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root

volumes: 
  my_mongodb:
